//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BitbookFinal.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Comment
    {
        public Comment()
        {
            this.Likes = new HashSet<Like>();
        }
    
        public string CommentId { get; set; }
        public string UserId { get; set; }
        public string CommentText { get; set; }
        public Nullable<System.DateTime> UpdateTime { get; set; }
        public string PostId { get; set; }
    
        public virtual AspNetUser AspNetUser { get; set; }
        public virtual Post Post { get; set; }
        public virtual ICollection<Like> Likes { get; set; }
    }
}
