//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BitbookFinal.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class FriendRelation
    {
        public Nullable<bool> AreFriend { get; set; }
        public string UserId1 { get; set; }
        public string UserId2 { get; set; }
    }
}
