//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BitbookFinal.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Like
    {
        public string LikeId { get; set; }
        public string UserId { get; set; }
        public string PostId { get; set; }
        public string CommentId { get; set; }
    
        public virtual AspNetUser AspNetUser { get; set; }
        public virtual Comment Comment { get; set; }
        public virtual Post Post { get; set; }
    }
}
